//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DAQ : global::System.Configuration.ApplicationSettingsBase {
        
        private static DAQ defaultInstance = ((DAQ)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DAQ())));
        
        public static DAQ Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Input Voltage")]
        public string inputVoltage {
            get {
                return ((string)(this["inputVoltage"]));
            }
            set {
                this["inputVoltage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Input Current")]
        public string inputCurrent {
            get {
                return ((string)(this["inputCurrent"]));
            }
            set {
                this["inputCurrent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beam Current Monitor")]
        public string beamCurrentMonitor {
            get {
                return ((string)(this["beamCurrentMonitor"]));
            }
            set {
                this["beamCurrentMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Beam Current Set Monitor")]
        public string beamCurrentSetMonitor {
            get {
                return ((string)(this["beamCurrentSetMonitor"]));
            }
            set {
                this["beamCurrentSetMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kV Monitor")]
        public string kVMonitor {
            get {
                return ((string)(this["kVMonitor"]));
            }
            set {
                this["kVMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kV Set Monitor")]
        public string kVSetMonitor {
            get {
                return ((string)(this["kVSetMonitor"]));
            }
            set {
                this["kVSetMonitor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kV Enable Analog")]
        public string kVEnableAnalog {
            get {
                return ((string)(this["kVEnableAnalog"]));
            }
            set {
                this["kVEnableAnalog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TFR")]
        public string tubeFilamentReady {
            get {
                return ((string)(this["tubeFilamentReady"]));
            }
            set {
                this["tubeFilamentReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Photo diode")]
        public string photoDiode {
            get {
                return ((string)(this["photoDiode"]));
            }
            set {
                this["photoDiode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kV Enable Digital")]
        public string kVEnableDigital {
            get {
                return ((string)(this["kVEnableDigital"]));
            }
            set {
                this["kVEnableDigital"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Interlock Feed Back")]
        public string interlock {
            get {
                return ((string)(this["interlock"]));
            }
            set {
                this["interlock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kV Set")]
        public string kVSet {
            get {
                return ((string)(this["kVSet"]));
            }
            set {
                this["kVSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uA Set")]
        public string beamCurrentSet {
            get {
                return ((string)(this["beamCurrentSet"]));
            }
            set {
                this["beamCurrentSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int numOfSamples {
            get {
                return ((int)(this["numOfSamples"]));
            }
            set {
                this["numOfSamples"] = value;
            }
        }
    }
}
